import { CardStyleId, CardThemeConfig } from '../types.ts';

export const CARD_THEMES: Record<CardStyleId, CardThemeConfig> = {
  'classic-gold': {
    id: 'classic-gold',
    name: 'Natural Olive & Marfil',
    badge: 'Tonos Naturales & Olivo',
    description: 'Guirnaldas botánicas de olivo y marfil cálido, estética serena y clásica mediterránea.',
    bgHex: '#FDFCF0',
    secondaryBgHex: '#FAF9F0',
    primaryColorHex: '#1a1a1a',
    accentColorHex: '#5A5A40',
    bgClass: 'bg-[#FDFCF0]',
    cardBgClass: 'bg-white text-[#1a1a1a] shadow-sm border border-[#E5E2D0]',
    textPrimaryClass: 'text-[#1a1a1a]',
    textSecondaryClass: 'text-[#5A5A40]',
    accentClass: 'text-[#5A5A40] bg-[#F9F7EF] border-[#E5E2D0]',
    borderClass: 'border-[#E5E2D0]',
    envelopeClass: 'bg-[#5A5A40]',
    envelopeLidClass: 'bg-[#484833]',
    sealBg: 'bg-gradient-to-br from-[#7D8C7A] via-[#5A5A40] to-[#3d3d2c] text-[#FDFCF0] shadow-stone-900/30',
    sealText: 'text-[#FDFCF0]',
    fontDisplay: 'font-["Playfair_Display"]',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'gold',
    transitionType: 'organic-wave',
    scrollbarTrackHex: 'rgba(229, 226, 208, 0.45)',
    scrollbarThumbHex: 'rgba(125, 140, 122, 0.7)',
    scrollbarThumbHoverHex: 'rgba(90, 90, 64, 0.95)',
  },
  'romantic-floral': {
    id: 'romantic-floral',
    name: 'Rosa Romántico & Flores',
    badge: 'Acuarela Floral',
    description: 'Arco de rosas inglesas en acuarela, tonos empolvados y cisnes reales entrelazados.',
    bgHex: '#FAF7F5',
    secondaryBgHex: '#F8F2EE',
    primaryColorHex: '#2A1F1D',
    accentColorHex: '#8A6D65',
    bgClass: 'bg-[#FAF7F5]',
    cardBgClass: 'bg-white text-stone-900 shadow-sm border border-[#E8DFD8]',
    textPrimaryClass: 'text-stone-900',
    textSecondaryClass: 'text-[#8A6D65]',
    accentClass: 'text-[#8A6D65] bg-[#F8F2EE] border-[#E8DFD8]',
    borderClass: 'border-[#E8DFD8]',
    envelopeClass: 'bg-[#7c5957]',
    envelopeLidClass: 'bg-[#674745]',
    sealBg: 'bg-gradient-to-br from-[#A88079] via-[#7c5957] to-[#543432] text-[#FDFCF0] shadow-stone-900/30',
    sealText: 'text-[#FDFCF0]',
    fontDisplay: 'font-["Playfair_Display"]',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'floral',
    transitionType: 'floral-arch',
    scrollbarTrackHex: 'rgba(232, 223, 216, 0.5)',
    scrollbarThumbHex: 'rgba(168, 128, 121, 0.7)',
    scrollbarThumbHoverHex: 'rgba(138, 109, 101, 0.95)',
  },
  'boho-chic': {
    id: 'boho-chic',
    name: 'Boho Terracota & Salvia',
    badge: 'Naturaleza & Boho',
    description: 'Hierbas de pampas secas, sol naciente bohemio y acentos cálidos de terracota.',
    bgHex: '#FAF8F2',
    secondaryBgHex: '#F3EFE6',
    primaryColorHex: '#2D2A26',
    accentColorHex: '#B26E59',
    bgClass: 'bg-[#FAF8F2]',
    cardBgClass: 'bg-white text-[#3D3D3D] shadow-sm border border-[#E8DFD2]',
    textPrimaryClass: 'text-[#2D2A26]',
    textSecondaryClass: '#7D8C7A',
    accentClass: 'text-[#B26E59] bg-[#FAF3ED] border-[#E8DFD2]',
    borderClass: 'border-[#E8DFD2]',
    envelopeClass: 'bg-[#7D8C7A]',
    envelopeLidClass: 'bg-[#687665]',
    sealBg: 'bg-gradient-to-br from-[#96A693] via-[#7D8C7A] to-[#556353] text-[#FDFCF0] shadow-stone-900/30',
    sealText: 'text-[#FDFCF0]',
    fontDisplay: 'font-["Montserrat"] font-semibold',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'boho',
    transitionType: 'boho-pampas',
    scrollbarTrackHex: 'rgba(232, 223, 210, 0.5)',
    scrollbarThumbHex: 'rgba(178, 110, 89, 0.65)',
    scrollbarThumbHoverHex: 'rgba(143, 79, 61, 0.95)',
  },
  'minimal-editorial': {
    id: 'minimal-editorial',
    name: 'Minimalista Editorial',
    badge: 'Vogue & Lino Natural',
    description: 'Líneas limpias, tipografía geométrica de alta costura y un diseño sereno contemporáneo.',
    bgHex: '#F9F7EF',
    secondaryBgHex: '#F2EFE3',
    primaryColorHex: '#141414',
    accentColorHex: '#4A4A3A',
    bgClass: 'bg-[#F9F7EF]',
    cardBgClass: 'bg-white text-[#1a1a1a] shadow-sm border border-[#E5E2D0]',
    textPrimaryClass: 'text-[#1a1a1a]',
    textSecondaryClass: 'text-[#5A5A40]',
    accentClass: 'text-[#1a1a1a] bg-[#FAF9F0] border-[#E5E2D0]',
    borderClass: 'border-[#E5E2D0]',
    envelopeClass: 'bg-[#2A2A26]',
    envelopeLidClass: 'bg-[#1D1D1A]',
    sealBg: 'bg-gradient-to-br from-[#5A5A40] via-[#3D3D2C] to-[#1D1D1A] text-[#FDFCF0] shadow-black/40',
    sealText: 'text-[#FDFCF0]',
    fontDisplay: 'font-["Montserrat"] uppercase tracking-widest',
    fontBody: 'font-["Montserrat"] font-light',
    ornamentStyle: 'minimal',
    transitionType: 'minimal-editorial',
    scrollbarTrackHex: 'rgba(229, 226, 208, 0.45)',
    scrollbarThumbHex: 'rgba(90, 90, 64, 0.6)',
    scrollbarThumbHoverHex: 'rgba(20, 20, 20, 0.9)',
  },
  'dark-luxury': {
    id: 'dark-luxury',
    name: 'Noche Olivo & Bronce',
    badge: 'Lujo Nocturno',
    description: 'Constelaciones estelares doradas y fondos oscuros en verde olivo profundo y bronce.',
    bgHex: '#1F211D',
    secondaryBgHex: '#181A16',
    primaryColorHex: '#FDFCF0',
    accentColorHex: '#C5A059',
    bgClass: 'bg-[#1F211D]',
    cardBgClass: 'bg-[#282B25] text-[#FDFCF0] shadow-xl border border-[#5A5A40]/50',
    textPrimaryClass: 'text-[#FDFCF0]',
    textSecondaryClass: 'text-[#C8D1C6]',
    accentClass: 'text-[#C5A059] bg-[#333830] border-[#5A5A40]',
    borderClass: 'border-[#5A5A40]',
    envelopeClass: 'bg-[#181A16]',
    envelopeLidClass: 'bg-[#121411]',
    sealBg: 'bg-gradient-to-br from-[#C5A059] via-[#947437] to-[#5A5A40] text-[#FDFCF0] shadow-black/60',
    sealText: 'text-[#FDFCF0]',
    fontDisplay: 'font-["Cinzel"]',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'stars',
    transitionType: 'celestial-night',
    scrollbarTrackHex: 'rgba(24, 26, 22, 0.7)',
    scrollbarThumbHex: 'rgba(90, 90, 64, 0.8)',
    scrollbarThumbHoverHex: 'rgba(197, 160, 89, 0.95)',
  },
  'watercolor-garden': {
    id: 'watercolor-garden',
    name: 'Jardín Botánico & Salvia',
    badge: 'Jardín & Follaje',
    description: 'Ramas de eucalipto en acuarela fresca, caligrafía romántica y tonos salvia exuberantes.',
    bgHex: '#FAFBF6',
    secondaryBgHex: '#F2F5EB',
    primaryColorHex: '#1D261C',
    accentColorHex: '#526B50',
    bgClass: 'bg-[#FAFBF6]',
    cardBgClass: 'bg-white text-[#1a1a1a] shadow-sm border border-[#DCE4DA]',
    textPrimaryClass: 'text-[#1a1a1a]',
    textSecondaryClass: 'text-[#526B50]',
    accentClass: 'text-[#526B50] bg-[#F4F7F1] border-[#DCE4DA]',
    borderClass: 'border-[#DCE4DA]',
    envelopeClass: 'bg-[#526B50]',
    envelopeLidClass: 'bg-[#3E523C]',
    sealBg: 'bg-gradient-to-br from-[#7D947B] via-[#526B50] to-[#31422F] text-[#FDFCF0] shadow-stone-900/40',
    sealText: 'text-[#FDFCF0]',
    fontDisplay: 'font-["Alex_Brush"] text-3xl',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'garden',
    transitionType: 'watercolor-garden',
    scrollbarTrackHex: 'rgba(220, 228, 218, 0.5)',
    scrollbarThumbHex: 'rgba(125, 148, 123, 0.7)',
    scrollbarThumbHoverHex: 'rgba(82, 107, 80, 0.95)',
  },
};

/**
 * Dynamically applies theme-reactive scrollbar colors to root document
 */
export function applyThemeScrollbar(cardStyle?: CardStyleId | string) {
  if (typeof document === 'undefined') return;
  const theme = (cardStyle && CARD_THEMES[cardStyle as CardStyleId]) || CARD_THEMES['classic-gold'];
  const root = document.documentElement;
  root.style.setProperty('--scrollbar-track', theme.scrollbarTrackHex || 'rgba(229, 226, 208, 0.45)');
  root.style.setProperty('--scrollbar-thumb', theme.scrollbarThumbHex || 'rgba(125, 140, 122, 0.7)');
  root.style.setProperty('--scrollbar-thumb-hover', theme.scrollbarThumbHoverHex || 'rgba(90, 90, 64, 0.95)');
}
