import { boolean, integer, pgTable, serial, text, timestamp, uniqueIndex, index } from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';

// Application user profiles for local-password and Google OAuth sign-in.
export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  uid: text('uid').notNull().unique(), // Auth UID
  email: text('email').notNull(),
  password: text('password'),
  name: text('name'),
  role: text('role').default('couple'), // 'ceo', 'wedding_planner', 'couple', 'admin'
  plan: text('plan').default('free'), // 'free', 'atelier', 'elite', 'planner_starter', 'planner_pro', 'ceo_unlimited'
  agencyName: text('agency_name'),
  phone: text('phone'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

// CEO-managed subscription plan overrides, persisted separately from source defaults.
export const subscriptionPlans = pgTable('subscription_plans', {
  planId: text('plan_id').primaryKey(),
  planData: text('plan_data').notNull(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

// Wedding global configuration
export const weddingSettings = pgTable('wedding_settings', {
  id: serial('id').primaryKey(),
  eventType: text('event_type').default('bodas'), // 'bodas' | 'xv'
  userId: integer('user_id'),
  ownerUid: text('owner_uid'),
  accessEmails: text('access_emails').array().notNull().default([]),
  clientEmail: text('client_email'),
  status: text('status').default('active'),
  slug: text('slug'),
  isPublished: boolean('is_published').default(true),
  coupleNames: text('couple_names').notNull().default('Sofía & Alejandro'),
  hashtag: text('hashtag').default('#BodaSofyAle2026'),
  hashtagIsCustom: boolean('hashtag_is_custom').default(false),
  eventDate: text('event_date').notNull().default('2026-11-28'),
  eventTime: text('event_time').notNull().default('17:00'),
  ceremonyVenue: text('ceremony_venue').notNull().default('Parroquia San Francisco de Asís'),
  ceremonyAddress: text('ceremony_address').notNull().default('Calle de los Olivos 142, Centro Histórico'),
  ceremonyMapsUrl: text('ceremony_maps_url').default('https://maps.google.com/?q=San+Francisco+Church'),
  ceremonyEmbedUrl: text('ceremony_embed_url').default(''),
  mapMobileWidth: integer('map_mobile_width').default(100),
  mapMobileHeight: integer('map_mobile_height').default(240),
  mapDesktopWidth: integer('map_desktop_width').default(100),
  mapDesktopHeight: integer('map_desktop_height').default(320),
  ceremonyArrivalVideoUrl: text('ceremony_arrival_video_url').default(''),
  ceremonyPlaceQuery: text('ceremony_place_query').default('Parroquia San Francisco de Asís'),
  ceremonyTime: text('ceremony_time').default('17:00'),
  receptionVenue: text('reception_venue').notNull().default('Hacienda Los Arcángeles'),
  receptionAddress: text('reception_address').notNull().default('Km 14.5 Carretera Real, Valle Encantado'),
  receptionSameAsCeremony: boolean('reception_same_as_ceremony').default(false),
  receptionMapsUrl: text('reception_maps_url').default('https://maps.google.com/?q=Hacienda+Los+Arcangeles'),
  receptionEmbedUrl: text('reception_embed_url').default(''),
  receptionArrivalVideoUrl: text('reception_arrival_video_url').default(''),
  receptionPlaceQuery: text('reception_place_query').default('Hacienda Los Arcángeles'),
  receptionTime: text('reception_time').default('19:30'),
  dressCode: text('dress_code').default('Formal / Traje Oscuro y Vestido Largo'),
  dressCodeDescription: text('dress_code_description').default('Agradecemos no usar blanco, marfil o champagne reservado para la novia.'),
  dressCodePalette: text('dress_code_palette').default('["#1C2D37", "#9E7D47", "#D4AF37", "#D8C7B8", "#4A5B52"]'),
  dressCodeMenTitle: text('dress_code_men_title').default('Para Ellos (Caballeros)'),
  dressCodeMenDescription: text('dress_code_men_description').default('Traje formal completo en tonos oscuros, camisa de vestir, corbata o moño y calzado de vestir.'),
  dressCodeWomenTitle: text('dress_code_women_title').default('Para Ellas (Damas)'),
  dressCodeWomenDescription: text('dress_code_women_description').default('Vestido largo de noche o gala en telas finas. Evitar tonos blancos o marfil.'),
  dressCodeFootwearNote: text('dress_code_footwear_note').default('Para áreas de jardín y pasto, sugerimos calzado de tacón ancho, cuña o flats elegantes.'),
  dressCodeProhibitedColors: text('dress_code_prohibited_colors').default('Colores blanco, marfil, perla y champaña claro reservados exclusivamente para la novia.'),
  dressCodeWomanOutfit: text('dress_code_woman_outfit').default('long-gown'),
  dressCodeManOutfit: text('dress_code_man_outfit').default('suit'),
  itinerary: text('itinerary').default('[{"time":"17:00","title":"Ceremonia Religiosa","desc":"Parroquia San Francisco de Asís","icon":"church"},{"time":"18:30","title":"Cóctel de Bienvenida","desc":"Jardín de los Naranjos","icon":"cocktail"},{"time":"20:00","title":"Banquete & Brindis","desc":"Salón Principal","icon":"utensils"},{"time":"22:00","title":"Fiesta & DJ","desc":"Pista de baile y barra libre","icon":"music"},{"time":"02:00","title":"Tornaboda & Chilaquiles","desc":"Terraza Nocturna","icon":"moon"}]'),
  giftRegistry: text('gift_registry').default('[]'),
  giftRegistryMessage: text('gift_registry_message').default(''),
  giftRegistryCopy: text('gift_registry_copy').default('{}'),
  coverPhoto: text('cover_photo').default('https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1600&q=80'),
  secondaryPhoto: text('secondary_photo').default('https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=80'),
  heroPhotos: text('hero_photos').default('["https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1600&q=80"]'),
  heroAutoplayInterval: integer('hero_autoplay_interval').default(5),
  cardStyle: text('card_style').default('classic-gold'), // 'classic-gold', 'romantic-floral', 'boho-chic', 'minimal-editorial', 'dark-luxury', 'watercolor-garden'
  envelopeColor: text('envelope_color').default('#2C2B29'),
  envelopeShadowColor: text('envelope_shadow_color').default('#2C211B'),
  envelopeShadowIntensity: integer('envelope_shadow_intensity').default(36),
  waxSealText: text('wax_seal_text').default('S&A'),
  waxSealTextIsCustom: boolean('wax_seal_text_is_custom').default(false),
  waxSealColor: text('wax_seal_color').default('#C5A059'),
  waxSealShadowColor: text('wax_seal_shadow_color').default('#211A14'),
  waxSealShadowIntensity: integer('wax_seal_shadow_intensity').default(55),
  audioUrl: text('audio_url').default('https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=acoustic-guitars-ambient-uplifting-112705.mp3'),
  audioTitle: text('audio_title').default('Acoustic Romance - Guitarra Suave'),
  audioAutoplay: boolean('audio_autoplay').default(false),
  audioPlaylist: text('audio_playlist').default(''),
  welcomeMessage: text('welcome_message').default('¡Nos casamos! Nos hace inmensa ilusión celebrar nuestro amor'),
  welcomeSubtitle: text('welcome_subtitle').default('Nos emociona compartir este día tan especial contigo. Aquí encontrarás todos los detalles y ubicaciones de nuestra celebración.'),
  heroDateFormat: text('hero_date_format').default('dd.mm.aaaa'),
  heroCustomDateText: text('hero_custom_date_text').default(''),
  heroQuote: text('hero_quote').default('El amor todo lo sufre, todo lo cree, todo lo espera, todo lo soporta.'),
  heroVerse: text('hero_verse').default('1 Corintios 13:7'),
  heroVersePosition: text('hero_verse_position').default('center'),
  heroShowCountdown: boolean('hero_show_countdown').default(false),
  heroShowRsvpButton: boolean('hero_show_rsvp_button').default(false),
  heroShowIcon: boolean('hero_show_icon').default(false),
  heroShowGuestPill: boolean('hero_show_guest_pill').default(false),
  heroShowPadrinos: boolean('hero_show_padrinos').default(false),
  heroPadrinosTitle: text('hero_padrinos_title').default('Nuestros Padrinos'),
  heroPadrinos: text('hero_padrinos').default(''),
  heroShowBrideParents: boolean('hero_show_bride_parents').default(false),
  heroBrideParentsTitle: text('hero_bride_parents_title').default('Padres de la Novia'),
  heroBrideParents: text('hero_bride_parents').default(''),
  heroShowGroomParents: boolean('hero_show_groom_parents').default(false),
  heroGroomParentsTitle: text('hero_groom_parents_title').default('Padres del Novio'),
  heroGroomParents: text('hero_groom_parents').default(''),
  heroShowWitnesses: boolean('hero_show_witnesses').default(false),
  heroWitnessesTitle: text('hero_witnesses_title').default('Testigos'),
  heroWitnesses: text('hero_witnesses').default(''),
  heroCourtPosition: text('hero_court_position').default('below-names'),
  heroCourtPlacement: text('hero_court_placement').default('hero'),
  heroCourtTitle: text('hero_court_title').default('Con la bendición de Dios y de nuestras familias'),
  heroCourtPageHeading: text('hero_court_page_heading').default('Con quienes celebramos este día'),
  showCountdown: boolean('show_countdown').default(true),
  countdownStyle: text('countdown_style').default('auto'),
  countdownLayout: text('countdown_layout').default('circle'),
  countdownTitle: text('countdown_title').default('Faltan'),
  countdownPlacement: text('countdown_placement').default('transition'),
  showCountdownGuestsBadge: boolean('show_countdown_guests_badge').default(true),
  colorPaletteStyle: text('color_palette_style').default('auto'),
  customAccentColor: text('custom_accent_color').default(''),
  customBgColor: text('custom_bg_color').default(''),
  fontPairStyle: text('font_pair_style').default('auto'),
  typographyTitleScale: integer('typography_title_scale').default(100),
  typographyHeadingScale: integer('typography_heading_scale').default(100),
  typographyBodyScale: integer('typography_body_scale').default(100),
  typographySubtitleScale: integer('typography_subtitle_scale').default(100),
  typographyDetailScale: integer('typography_detail_scale').default(100),
  typographyBadgeScale: integer('typography_badge_scale').default(100),
  typographyButtonScale: integer('typography_button_scale').default(100),
  typographyToggleScale: integer('typography_toggle_scale').default(100),
  typographyGalleryFullscreenScale: integer('typography_gallery_fullscreen_scale').default(100),
  typographyNumberFont: text('typography_number_font').default('theme'),
  typographyHeroNumberFont: text('typography_hero_number_font').default('global'),
  typographyCountdownNumberFont: text('typography_countdown_number_font').default('global'),
  dividerStyle: text('divider_style').default('auto'),
  showCardDividers: boolean('show_card_dividers').default(false),
  borderlessCards: boolean('borderless_cards').default(false),
  transparentCards: boolean('transparent_cards').default(false),
  frameOrnamentStyle: text('frame_ornament_style').default('auto'),
  transitionWaveStyle: text('transition_wave_style').default('auto'),
  transitionEffect: text('transition_effect').default('wave'),
  heroIconStyle: text('hero_icon_style').default('auto'),
  heroEmblemColor: text('hero_emblem_color').default(''),
  heroEmblemGlow: integer('hero_emblem_glow').default(72),
  heroEmblemSparkle: integer('hero_emblem_sparkle').default(78),
  heroEmblemScale: integer('hero_emblem_scale').default(100),
  ambientParticleStyle: text('ambient_particle_style').default('auto'),
  sealStyle: text('seal_style').default('auto'),
  showInvitationLetter: boolean('show_invitation_letter').notNull().default(true),
  letterBackgroundColor: text('letter_background_color').default(''),
  letterPaperColor: text('letter_paper_color').default(''),
  letterTextColor: text('letter_text_color').default(''),
  letterAccentColor: text('letter_accent_color').default(''),
  letterHeroColor: text('letter_hero_color').default(''),
  letterMotifColor: text('letter_motif_color').default(''),
  letterFrameColor: text('letter_frame_color').default(''),
  letterShowCardBorder: boolean('letter_show_card_border').notNull().default(true),
  letterShowCornerMotifs: boolean('letter_show_corner_motifs').notNull().default(true),
  letterHeadingText: text('letter_heading_text').default(''),
  letterNamesText: text('letter_names_text').default(''),
  letterDateText: text('letter_date_text').default(''),
  letterMessageText: text('letter_message_text').default(''),
  letterReservationHeadingText: text('letter_reservation_heading_text').default(''),
  letterReservationSingleText: text('letter_reservation_single_text').default(''),
  letterReservationPluralText: text('letter_reservation_plural_text').default(''),
  letterGuestLabelText: text('letter_guest_label_text').default(''),
  letterCtaText: text('letter_cta_text').default(''),
  letterOpeningText: text('letter_opening_text').default(''),
  letterSignoffText: text('letter_signoff_text').default(''),
  letterDividerColor: text('letter_divider_color').default(''),
  letterArrowColor: text('letter_arrow_color').default(''),
  letterDisplayFont: text('letter_display_font').default('auto'),
  letterBodyFont: text('letter_body_font').default('auto'),
  letterFrameStyle: text('letter_frame_style').default('auto'),
  letterMotifStyle: text('letter_motif_style').default('auto'),
  letterDividerStyle: text('letter_divider_style').default('auto'),
  heroImageFit: text('hero_image_fit').default('cover'),
  heroImagePosition: text('hero_image_position').default('center'),
  heroOverlayOpacity: integer('hero_overlay_opacity').default(40),
  heroEnableScrollBlur: boolean('hero_enable_scroll_blur').default(true),
  showItinerary: boolean('show_itinerary').default(true),
  showLocations: boolean('show_locations').default(true),
  showDressCode: boolean('show_dress_code').default(true),
  showGiftRegistry: boolean('show_gift_registry').default(false),
  showPhotoGallery: boolean('show_photo_gallery').default(true),
  gallerySectionEyebrow: text('gallery_section_eyebrow').default('Sesión de Fotos & Recuerdos'),
  gallerySectionTitle: text('gallery_section_title').default(''),
  galleryPhotoPromptText: text('gallery_photo_prompt_text').default('Presiona en la foto'),
  galleryEmptyTitle: text('gallery_empty_title').default('Galería en preparación'),
  galleryEmptyDescription: text('gallery_empty_description').default(''),
  galleryDrivePhotoBadgeText: text('gallery_drive_photo_badge_text').default('Google Drive'),
  gallerySharedAlbumCaption: text('gallery_shared_album_caption').default('Fotos compartidas'),
  galleryCommentsButtonText: text('gallery_comments_button_text').default('Comentar'),
  galleryCommentsCountLabel: text('gallery_comments_count_label').default('Comentarios'),
  galleryCommentsPromptText: text('gallery_comments_prompt_text').default('Ver y dejar comentarios ({count})...'),
  galleryFullscreenCommentsTitle: text('gallery_fullscreen_comments_title').default('Comentarios & Dedicatorias'),
  galleryCommentsLoadingText: text('gallery_comments_loading_text').default('Cargando comentarios...'),
  galleryCommentsEmptyText: text('gallery_comments_empty_text').default('Sé el primero en comentar esta foto'),
  galleryCommentsHelperText: text('gallery_comments_helper_text').default('Deja un lindo mensaje o dedicatoria.'),
  galleryCommentNameLabel: text('gallery_comment_name_label').default('Tu nombre'),
  galleryCommentNamePlaceholder: text('gallery_comment_name_placeholder').default('Tu nombre (ej. Familia Pérez)'),
  galleryCommentTextLabel: text('gallery_comment_text_label').default('Comentario'),
  galleryCommentTextPlaceholder: text('gallery_comment_text_placeholder').default('Escribe un comentario o dedicatoria...'),
  galleryCommentSubmitText: text('gallery_comment_submit_text').default('Enviar'),
  galleryExternalAlbumUrl: text('gallery_external_album_url').default(''),
  galleryExternalAlbumTitle: text('gallery_external_album_title').default('Álbum en Google Photos'),
  galleryExternalAlbumType: text('gallery_external_album_type').default('google_photos'),
  galleryDrivePhotoSelectionMode: text('gallery_drive_photo_selection_mode').default('all'),
  galleryDrivePhotoIds: text('gallery_drive_photo_ids').default('[]'),
  galleryDrivePhotoTitles: text('gallery_drive_photo_titles').default('{}'),
  showVideoMemories: boolean('show_video_memories').default(false),
  showGuestbook: boolean('show_guestbook').default(false),
  showHotels: boolean('show_hotels').default(false),
  hotelsTitle: text('hotels_title').default('Hospedaje recomendado'),
  hotelRecommendations: text('hotel_recommendations').default('[]'),
  landingSectionOrder: text('landing_section_order').default('["invitation","gallery","video","hotels","guestbook","rsvp"]'),
  detailSectionOrder: text('detail_section_order').default('["ceremony","reception","rsvp","itinerary","gifts","dress-code","tips"]'),
  galleryPlacement: text('gallery_placement').default('landing'),
  galleryAfterDetailSection: text('gallery_after_detail_section').default('reception'),
  showTips: boolean('show_tips').default(true),
  tipsTitle: text('tips_title').default('Tips & Recomendaciones para Invitados'),
  tipsList: text('tips_list').default('[{"icon":"clock","title":"Puntualidad","desc":"Agradecemos llegar 15 minutos antes de la ceremonia para comenzar a tiempo."},{"icon":"car","title":"Estacionamiento & Valet","desc":"El recinto cuenta con servicio de Valet Parking y vigilancia privada."},{"icon":"camera","title":"Fotografías & Momentos","desc":"¡Comparte tus fotos en nuestra galería en vivo o usando nuestro hashtag oficial!"},{"icon":"heart","title":"Niños / Solo Adultos","desc":"Hemos preparado una celebración de gala para adultos. ¡Disfrutemos juntos la noche!"}]'),
  showRsvpSection: boolean('show_rsvp_section').default(true),
  rsvpDeadlineMessage: text('rsvp_deadline_message').default('Por favor confirma tu asistencia antes del {date}.'),
  shareMessageTemplate: text('share_message_template').default('💌 ¡Estás invitado/a!\n\n{coupleNames} te invita a celebrar este día tan especial. ✨\n📅 {eventDate}\n\nConfirma tu asistencia aquí:\n{url}\n\n¡Te esperamos! 💛'),
  rsvpButtonText: text('rsvp_button_text').default('Confirmar asistencia'),
  rsvpButtonStyle: text('rsvp_button_style').default('auto'),
  rsvpCompanionToggleText: text('rsvp_companion_toggle_text').default('¿Llevas invitados?'),
  rsvpMaxCompanions: integer('rsvp_max_companions').default(5),
  rsvpOptionalFields: text('rsvp_optional_fields').default('[{"id":"dietaryRestrictions","label":"Restricciones alimentarias / alergias","placeholder":"Ej. vegetariano, celíaco, alergia...","type":"text"},{"id":"suggestedSong","label":"Canción para la fiesta (DJ)","placeholder":"Ej. Vivir Mi Vida - Marc Anthony","type":"text"},{"id":"message","label":"Mensaje o dedicatoria para los anfitriones","placeholder":"Escribe unas palabras de felicitación o buenos deseos...","type":"textarea"},{"id":"phone","label":"Teléfono / WhatsApp","placeholder":"Ej. +51 987 654 321","type":"tel"},{"id":"email","label":"Correo electrónico","placeholder":"correo@ejemplo.com","type":"email"}]'),
  rsvpAllowRegistration: boolean('rsvp_allow_registration').default(true),
  rsvpRegistrationCutoffMode: text('rsvp_registration_cutoff_mode').default('event'),
  rsvpRegistrationCutoffAt: text('rsvp_registration_cutoff_at').default(''),
  rsvpAllowEdit: boolean('rsvp_allow_edit').default(true),
  rsvpEditCutoffMode: text('rsvp_edit_cutoff_mode').default('event'),
  rsvpEditCutoffAt: text('rsvp_edit_cutoff_at').default(''),
  rsvpCutoffTimeZone: text('rsvp_cutoff_time_zone').default('America/Lima'),
  bankName: text('bank_name').default(''),
  bankBeneficiary: text('bank_beneficiary').default(''),
  bankAccountNumber: text('bank_account_number').default(''),
  bankClabe: text('bank_clabe').default(''),
  bankCardNumber: text('bank_card_number').default(''),
  bankConcept: text('bank_concept').default('Evento Sofía & Alejandro'),
  bankCurrency: text('bank_currency').default('MXN'),
  bankAccounts: text('bank_accounts').default('[]'),
  enableBankTransfer: boolean('enable_bank_transfer').default(false),
  showBankAccountsWhenCollapsed: boolean('show_bank_accounts_when_collapsed').default(true),
  enableStoreRegistry: boolean('enable_store_registry').default(false),
  enableEnvelopeGift: boolean('enable_envelope_gift').default(false),
  envelopeGiftMessage: text('envelope_gift_message').default('Lluvia de sobres: Si deseas hacernos un regalo en efectivo el día del evento, dispondremos de un cofre especial en la recepción.'),
  rsvpDeadline: text('rsvp_deadline').default('2026-10-30'),
  contactPhone: text('contact_phone').default('+52 55 1234 5678'),
  contactEmail: text('contact_email').default('boda.sofyale@gmail.com'),
  updatedAt: timestamp('updated_at').defaultNow(),
});

// Guests and invitations table
export const guests = pgTable('guests', {
  id: serial('id').primaryKey(),
  weddingId: integer('wedding_id').default(1),
  accessCode: text('access_code').notNull().unique(), // e.g. "FLOP-892" or slug
  fullName: text('full_name').notNull(),
  email: text('email'),
  phone: text('phone'),
  groupName: text('group_name').default('Familiares'),
  allocatedPasses: integer('allocated_passes').notNull().default(2),
  confirmedPasses: integer('confirmed_passes').default(0),
  status: text('status').notNull().default('pending'), // 'pending', 'confirmed', 'declined'
  attendingCeremony: boolean('attending_ceremony').default(true),
  attendingReception: boolean('attending_reception').default(true),
  dietaryRestrictions: text('dietary_restrictions').default(''),
  companionNames: text('companion_names').default('[]'), // JSON array of accompanying guests; excludes fullName
  suggestedSong: text('suggested_song').default(''),
  message: text('message').default(''),
  customRsvpDetails: text('custom_rsvp_details').default('{}'),
  confirmedAt: timestamp('confirmed_at'),
  viewedAt: timestamp('viewed_at'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

// Photo gallery shared by guests and couple
export const galleryPhotos = pgTable('gallery_photos', {
  id: serial('id').primaryKey(),
  weddingId: integer('wedding_id').default(1),
  url: text('url').notNull(),
  thumbnailUrl: text('thumbnail_url'),
  caption: text('caption'),
  authorName: text('author_name').notNull().default('Invitado Especial'),
  guestCode: text('guest_code'),
  category: text('category').default('fiesta'), // 'preparativos', 'ceremonia', 'brindis', 'fiesta', 'recuerdos'
  likesCount: integer('likes_count').default(0),
  approved: boolean('approved').default(true),
  createdAt: timestamp('created_at').defaultNow(),
});

// Videos (YouTube, Instagram, Facebook, TikTok)
export const weddingVideos = pgTable('wedding_videos', {
  id: serial('id').primaryKey(),
  weddingId: integer('wedding_id').default(1),
  title: text('title').notNull(),
  platform: text('platform').notNull(), // 'youtube', 'instagram', 'facebook', 'tiktok', 'vimeo', 'direct'
  videoUrl: text('video_url').notNull(),
  embedId: text('embed_id'),
  description: text('description'),
  authorName: text('author_name').default('Novios'),
  createdAt: timestamp('created_at').defaultNow(),
});

// Guestbook wishes and congratulations
export const guestbookWishes = pgTable('guestbook_wishes', {
  id: serial('id').primaryKey(),
  weddingId: integer('wedding_id').default(1),
  guestName: text('guest_name').notNull(),
  relationship: text('relationship').default('Amigo / Familiar'),
  message: text('message').notNull(),
  avatarUrl: text('avatar_url'),
  isHighlighted: boolean('is_highlighted').default(false),
  createdAt: timestamp('created_at').defaultNow(),
});

// Photo comments by guests
export const photoComments = pgTable('photo_comments', {
  id: serial('id').primaryKey(),
  photoId: integer('photo_id').notNull(),
  weddingId: integer('wedding_id').default(1),
  guestName: text('guest_name').notNull().default('Invitado Especial'),
  guestCode: text('guest_code'),
  message: text('message').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
});

// Engagement for public Google Drive photos is keyed by event and Drive file ID,
// never by a carousel position or the synthetic gallery photo ID.
export const drivePhotoInteractions = pgTable('drive_photo_interactions', {
  id: serial('id').primaryKey(),
  weddingId: integer('wedding_id').notNull(),
  driveFileId: text('drive_file_id').notNull(),
  likesCount: integer('likes_count').notNull().default(0),
  createdAt: timestamp('created_at').defaultNow(),
}, (table) => ({
  eventFileUnique: uniqueIndex('drive_photo_interactions_event_file_uidx').on(table.weddingId, table.driveFileId),
}));

export const drivePhotoComments = pgTable('drive_photo_comments', {
  id: serial('id').primaryKey(),
  weddingId: integer('wedding_id').notNull(),
  driveFileId: text('drive_file_id').notNull(),
  guestName: text('guest_name').notNull().default('Invitado Especial'),
  guestCode: text('guest_code'),
  message: text('message').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
}, (table) => ({
  eventFileCreatedIdx: index('drive_photo_comments_event_file_created_idx').on(table.weddingId, table.driveFileId, table.createdAt),
}));

// Relations
export const usersRelations = relations(users, () => ({}));
