import { WeddingSettings } from '../types.ts';

export const DEFAULT_XV_SETTINGS: WeddingSettings = {
  id: 2,
  eventType: 'xv',
  userId: 1,
  ownerUid: 'demo-user-xv',
  slug: 'xv-valeria-montserrat',
  coupleNames: 'Valeria Montserrat',
  hashtag: '#MisXValeria2026',
  eventDate: '2026-10-17',
  eventTime: '18:00',
  ceremonyVenue: 'Catedral Metropolitana / Misa de Acción de Gracias',
  ceremonyAddress: 'Plaza de la Constitución S/N, Centro Histórico',
  ceremonyMapsUrl: 'https://maps.google.com/?q=Catedral+Metropolitana',
  ceremonyEmbedUrl: '',
  ceremonyPlaceQuery: 'Catedral Metropolitana',
  ceremonyTime: '18:00',
  receptionVenue: 'Salón Diamante & Jardines de Versalles',
  receptionAddress: 'Av. Las Palmas 550, Zona Residencial Real',
  receptionMapsUrl: 'https://maps.google.com/?q=Salon+Diamante',
  receptionEmbedUrl: '',
  receptionPlaceQuery: 'Salón Diamante',
  receptionTime: '20:00',
  dressCode: 'Rigurosa Etiqueta / Gala Juvenil',
  dressCodeDescription: 'Agradezco a mis invitados reservar los tonos Rosa Pastel, Palo de Rosa y Blanco para mí como Quinceañera.',
  dressCodePalette: JSON.stringify(['#F4C2C2', '#DDA0DD', '#E6C280', '#2C3E50', '#7D5A85']),
  dressCodeMenTitle: 'Caballeros / Jóvenes',
  dressCodeMenDescription: 'Traje formal oscuro, camisa de vestir y corbata elegante.',
  dressCodeWomenTitle: 'Damas y Señoritas',
  dressCodeWomenDescription: 'Vestido largo de fiesta o cóctel sofisticado en tonos libres.',
  dressCodeFootwearNote: '¡Ven con calzado cómodo para no parar de bailar toda la noche!',
  dressCodeProhibitedColors: 'Rosa Pastel, Palo de Rosa y Blanco Puro (Reservados para la Quinceañera)',
  dressCodeStylePreset: 'formal',
  dressCodeWomanOutfit: 'long-gown',
  dressCodeManOutfit: 'suit',
  itinerary: JSON.stringify([
    { time: '18:00', title: 'Misa de Acción de Gracias', desc: 'Catedral Metropolitana', icon: 'church' },
    { time: '19:30', title: 'Recepción & Alfombra Rosa', desc: 'Cóctel de bienvenida en Jardines', icon: 'cocktail' },
    { time: '20:45', title: 'Mi Entrada Triunfal', desc: 'Pasarela de gala y fanfarria real', icon: 'sparkles' },
    { time: '21:15', title: 'Mi Vals Principal & Baile con Papá', desc: 'Vals familiar y Corte de Honor', icon: 'music' },
    { time: '21:45', title: 'Cambio de Zapatilla & Coronación', desc: 'Tradición y entrega de tiara de cristal', icon: 'crown' },
    { time: '22:15', title: 'Cena de Gala & Brindis', desc: 'Banquete de tres tiempos y postre especial', icon: 'utensils' },
    { time: '23:00', title: 'Show de Baile Moderno & DJ', desc: 'Sorpresa con mis chambelanes y pista abierta', icon: 'music' },
    { time: '02:30', title: 'Tornamesa & Chilaquiles', desc: 'Desvelada con mis mejores amigos', icon: 'moon' },
  ]),
  giftRegistry: JSON.stringify([
    {
      type: 'bank',
      title: 'Fondo Mis XV & Viaje Soñado',
      accountNumber: '9876-5432-1098-7654',
      clabe: '012180098765432109',
      bankName: 'BBVA',
      beneficiary: 'Valeria Montserrat Gómez',
      concept: 'Regalo XV Valeria',
    },
    {
      type: 'store',
      title: 'Mesa de Regalos Liverpool XV',
      url: 'https://mesaderegalos.liverpool.com.mx',
      eventNumber: '9823412',
    },
    {
      type: 'honeymoon',
      title: 'Fondo de Estudios & Recuerdos',
      description: 'Tu cariño y presencia son mi mejor regalo. Si deseas hacerme un detalle, puedes apoyar mi meta académica y viaje soñado.',
      url: 'https://paypal.me/misxvaleria',
    },
  ]),
  coverPhoto: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=1600&q=80',
  secondaryPhoto: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?auto=format&fit=crop&w=1200&q=80',
  heroImageFit: 'cover',
  heroImagePosition: 'center',
  heroOverlayOpacity: 35,
  heroEnableScrollBlur: true,
  cardStyle: 'romantic-floral',
  envelopeColor: '#3B2338',
  waxSealText: 'XV',
  waxSealColor: '#D4AF37',
  audioUrl: '/audio/vals-danubio-azul.mp3',
  audioTitle: 'Vals de Ensueño - Gran Orquesta Real',
  audioAutoplay: false,
  welcomeMessage: '¡Mis Quince Años! Un sueño hecho realidad',
  welcomeSubtitle: 'Doy gracias a Dios y a mis queridos padres por permitirme llegar a esta hermosa etapa. Será un inmenso honor contar con tu compañía en mi noche inolvidable.',
  heroDateFormat: 'dd.mm.aaaa',
  heroCustomDateText: '',
  heroQuote: 'Deja que la vida te despeine, sueña en grande y baila como si el mundo fuera tuyo.',
  heroVerse: 'Proverbios 31:25 - Fuerza y dignidad son su vestidura, y se ríe de lo por venir.',
  heroShowCountdown: true,
  heroShowRsvpButton: true,
  heroShowIcon: true,
  heroShowGuestPill: true,
  showItinerary: true,
  showLocations: true,
  showDressCode: true,
  showGiftRegistry: true,
  showPhotoGallery: true,
  galleryExternalAlbumUrl: '',
  galleryExternalAlbumTitle: 'Galería de Mis XV',
  galleryExternalAlbumType: 'google_photos',
  showVideoMemories: true,
  showGuestbook: true,
  showHotels: false,
  showRsvpSection: true,
  bankName: 'BBVA',
  bankBeneficiary: 'Valeria Montserrat Gómez',
  bankAccountNumber: '9876 5432 1098 7654',
  bankClabe: '012180098765432109',
  bankCardNumber: '',
  bankConcept: 'Regalo Mis XV Valeria',
  bankCurrency: 'MXN',
  enableBankTransfer: true,
  enableStoreRegistry: true,
  enableEnvelopeGift: true,
  envelopeGiftMessage: 'Lluvia de sobres: Si deseas hacerme un obsequio en efectivo el día de mi fiesta, pondré a tu disposición un buzón especial en la entrada.',
  customStoreItems: [],
  rsvpDeadline: '2026-09-25',
  contactPhone: '+52 55 9876 5432',
  contactEmail: 'xv.valeriamontserrat@gmail.com',
  isPublished: true,
};
