import { CardStyleId, CardThemeConfig } from '../types.ts';

export const XV_CARD_THEMES: Record<CardStyleId, CardThemeConfig> = {
  'romantic-floral': {
    id: 'romantic-floral',
    name: 'Rose Gold & Princesa Real',
    badge: 'Corona & Palo de Rosa',
    description: 'Tonos rosa pastel y blush, destellos de oro rosa, diadema de princesa y tiara luminosa.',
    bgHex: '#FDF7F9',
    secondaryBgHex: '#F9ECF1',
    primaryColorHex: '#301924',
    accentColorHex: '#B85D83',
    bgClass: 'bg-[#FDF7F9]',
    cardBgClass: 'bg-white/95 text-stone-900 shadow-sm border border-[#F3D7E3]',
    textPrimaryClass: 'text-[#301924]',
    textSecondaryClass: 'text-[#B85D83]',
    accentClass: 'text-[#B85D83] bg-[#FDF0F5] border-[#F3D7E3]',
    borderClass: 'border-[#F3D7E3]',
    envelopeClass: 'bg-[#7A3654]',
    envelopeLidClass: 'bg-[#632B44]',
    sealBg: 'bg-gradient-to-br from-[#E8A5BF] via-[#B85D83] to-[#7A3654] text-[#FFF] shadow-pink-900/30',
    sealText: 'text-white',
    fontDisplay: 'font-["Playfair_Display"]',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'floral',
    transitionType: 'floral-arch',
    scrollbarTrackHex: 'rgba(243, 215, 227, 0.5)',
    scrollbarThumbHex: 'rgba(184, 93, 131, 0.7)',
    scrollbarThumbHoverHex: 'rgba(122, 54, 84, 0.95)',
    cardShapeClass: 'rounded-tl-[3rem] rounded-br-[3rem] rounded-tr-xl rounded-bl-xl border-t-2 border-t-[#B85D83]/40 border-b-2 border-b-[#B85D83]/30 ring-1 ring-[#F3D7E3]',
    cardHeaderShapeClass: 'rounded-tl-2xl rounded-br-2xl bg-[#B85D83]/10 border border-[#B85D83]/20',
    cardBorderDecoration: 'shadow-[0_8px_30px_rgb(184,93,131,0.12)]',
    cardLayoutVariant: 'standard',
  },
  'classic-gold': {
    id: 'classic-gold',
    name: 'Dorado Real & Tiara de Cristal',
    badge: 'Gala & Corona Dorada',
    description: 'Majestuoso dorado champán, blanco marfil y ornamentos de alta costura para quinceañera.',
    bgHex: '#FDFBF7',
    secondaryBgHex: '#F7F3EA',
    primaryColorHex: '#261F12',
    accentColorHex: '#B38B38',
    bgClass: 'bg-[#FDFBF7]',
    cardBgClass: 'bg-white text-[#261F12] shadow-sm border border-[#EDE3CF]',
    textPrimaryClass: 'text-[#261F12]',
    textSecondaryClass: 'text-[#B38B38]',
    accentClass: 'text-[#B38B38] bg-[#FAF5EB] border-[#EDE3CF]',
    borderClass: 'border-[#EDE3CF]',
    envelopeClass: 'bg-[#47391F]',
    envelopeLidClass: 'bg-[#362B16]',
    sealBg: 'bg-gradient-to-br from-[#E0C070] via-[#B38B38] to-[#805F19] text-[#FFF] shadow-amber-900/30',
    sealText: 'text-white',
    fontDisplay: 'font-["Playfair_Display"]',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'gold',
    transitionType: 'organic-wave',
    scrollbarTrackHex: 'rgba(237, 227, 207, 0.45)',
    scrollbarThumbHex: 'rgba(179, 139, 56, 0.7)',
    scrollbarThumbHoverHex: 'rgba(128, 95, 25, 0.95)',
    cardShapeClass: 'rounded-t-[2.5rem] rounded-b-2xl border-t-2 border-t-[#B38B38]/40 ring-1 ring-[#EDE3CF]',
    cardHeaderShapeClass: 'rounded-2xl bg-[#B38B38]/10 border border-[#B38B38]/20',
    cardBorderDecoration: 'shadow-[0_8px_30px_rgb(179,139,56,0.10)]',
    cardLayoutVariant: 'standard',
  },
  'lavender-provence': {
    id: 'lavender-provence',
    name: 'Sweet Lavanda & Mariposas',
    badge: 'Lilas & Hadas de Ensueño',
    description: 'Suaves violetas y lilas pastel, atmósfera mágica de juventud y mariposas de fantasía.',
    bgHex: '#F8F6FC',
    secondaryBgHex: '#F0ECFA',
    primaryColorHex: '#251936',
    accentColorHex: '#7C5EA0',
    bgClass: 'bg-[#F8F6FC]',
    cardBgClass: 'bg-white/95 text-[#251936] shadow-sm border border-[#E4DCF5]',
    textPrimaryClass: 'text-[#251936]',
    textSecondaryClass: 'text-[#7C5EA0]',
    accentClass: 'text-[#7C5EA0] bg-[#F5F0FD] border-[#E4DCF5]',
    borderClass: 'border-[#E4DCF5]',
    envelopeClass: 'bg-[#4F366E]',
    envelopeLidClass: 'bg-[#3F2B57]',
    sealBg: 'bg-gradient-to-br from-[#A588CC] via-[#7C5EA0] to-[#4F366E] text-[#FFF] shadow-purple-900/30',
    sealText: 'text-white',
    fontDisplay: 'font-["Playfair_Display"]',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'lavender',
    transitionType: 'floral-arch',
    scrollbarTrackHex: 'rgba(228, 220, 245, 0.5)',
    scrollbarThumbHex: 'rgba(124, 94, 160, 0.7)',
    scrollbarThumbHoverHex: 'rgba(79, 54, 110, 0.95)',
    cardShapeClass: 'rounded-t-[3rem] rounded-b-2xl border-t-2 border-t-[#7C5EA0]/40 ring-1 ring-[#E4DCF5]',
    cardHeaderShapeClass: 'rounded-2xl bg-[#7C5EA0]/10 border border-[#7C5EA0]/20',
    cardBorderDecoration: 'shadow-[0_8px_30px_rgb(124,94,160,0.12)]',
    cardLayoutVariant: 'standard',
  },
  'emerald-botanical': {
    id: 'emerald-botanical',
    name: 'Esmeralda de Gala & Oro',
    badge: 'Alta Costura XV',
    description: 'Verde esmeralda sofisticado con acentos dorados reales para una quinceañera moderna y elegante.',
    bgHex: '#F5F9F7',
    secondaryBgHex: '#EBF4F0',
    primaryColorHex: '#12261E',
    accentColorHex: '#2D6E54',
    bgClass: 'bg-[#F5F9F7]',
    cardBgClass: 'bg-white/95 text-[#12261E] shadow-sm border border-[#CEE3D8]',
    textPrimaryClass: 'text-[#12261E]',
    textSecondaryClass: 'text-[#2D6E54]',
    accentClass: 'text-[#2D6E54] bg-[#F0F7F3] border-[#CEE3D8]',
    borderClass: 'border-[#CEE3D8]',
    envelopeClass: 'bg-[#1C4233]',
    envelopeLidClass: 'bg-[#153327]',
    sealBg: 'bg-gradient-to-br from-[#53A381] via-[#2D6E54] to-[#1C4233] text-[#FFF] shadow-emerald-900/30',
    sealText: 'text-white',
    fontDisplay: 'font-["Playfair_Display"]',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'botanical',
    transitionType: 'emerald-palms',
    scrollbarTrackHex: 'rgba(206, 227, 216, 0.5)',
    scrollbarThumbHex: 'rgba(45, 110, 84, 0.7)',
    scrollbarThumbHoverHex: 'rgba(28, 66, 51, 0.95)',
    cardShapeClass: 'rounded-2xl border border-[#CEE3D8]',
    cardHeaderShapeClass: 'rounded-xl bg-[#2D6E54]/10 border border-[#2D6E54]/20',
    cardBorderDecoration: 'shadow-[0_8px_30px_rgb(45,110,84,0.10)]',
    cardLayoutVariant: 'standard',
  },
  'royal-navy': {
    id: 'royal-navy',
    name: 'Noche de Estrellas & Tiara Zafiro',
    badge: 'Midnight Fantasy',
    description: 'Azul noche profundo, destellos de cristal plateado y constelaciones para una noche inolvidable.',
    bgHex: '#F4F7FB',
    secondaryBgHex: '#E8F0F8',
    primaryColorHex: '#0E1F36',
    accentColorHex: '#255085',
    bgClass: 'bg-[#F4F7FB]',
    cardBgClass: 'bg-white/95 text-[#0E1F36] shadow-sm border border-[#CFE0F2]',
    textPrimaryClass: 'text-[#0E1F36]',
    textSecondaryClass: 'text-[#255085]',
    accentClass: 'text-[#255085] bg-[#EFF6FD] border-[#CFE0F2]',
    borderClass: 'border-[#CFE0F2]',
    envelopeClass: 'bg-[#152E52]',
    envelopeLidClass: 'bg-[#0E203B]',
    sealBg: 'bg-gradient-to-br from-[#457BBB] via-[#255085] to-[#152E52] text-[#FFF] shadow-blue-900/30',
    sealText: 'text-white',
    fontDisplay: 'font-["Playfair_Display"]',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'navy',
    transitionType: 'royal-crest',
    scrollbarTrackHex: 'rgba(207, 224, 242, 0.5)',
    scrollbarThumbHex: 'rgba(37, 80, 133, 0.7)',
    scrollbarThumbHoverHex: 'rgba(21, 46, 82, 0.95)',
    cardShapeClass: 'rounded-t-[2.5rem] rounded-b-2xl border-t-2 border-t-[#255085]/40 ring-1 ring-[#CFE0F2]',
    cardHeaderShapeClass: 'rounded-2xl bg-[#255085]/10 border border-[#255085]/20',
    cardBorderDecoration: 'shadow-[0_8px_30px_rgb(37,80,133,0.12)]',
    cardLayoutVariant: 'standard',
  },
  'champagne-glam': {
    id: 'champagne-glam',
    name: 'Glamour Rose Gold & Brillos',
    badge: 'Chic & Champagne',
    description: 'Brillo radiante, destellos perlados y detalles de joyería fina para la fiesta de 15.',
    bgHex: '#FBF9F7',
    secondaryBgHex: '#F6F0E9',
    primaryColorHex: '#2B231D',
    accentColorHex: '#A37750',
    bgClass: 'bg-[#FBF9F7]',
    cardBgClass: 'bg-white/95 text-[#2B231D] shadow-sm border border-[#EDDFD1]',
    textPrimaryClass: 'text-[#2B231D]',
    textSecondaryClass: 'text-[#A37750]',
    accentClass: 'text-[#A37750] bg-[#FAF4ED] border-[#EDDFD1]',
    borderClass: 'border-[#EDDFD1]',
    envelopeClass: 'bg-[#573E28]',
    envelopeLidClass: 'bg-[#422F1E]',
    sealBg: 'bg-gradient-to-br from-[#CF9F74] via-[#A37750] to-[#573E28] text-[#FFF] shadow-amber-900/30',
    sealText: 'text-white',
    fontDisplay: 'font-["Playfair_Display"]',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'champagne',
    transitionType: 'champagne-sparkle',
    scrollbarTrackHex: 'rgba(237, 223, 209, 0.5)',
    scrollbarThumbHex: 'rgba(163, 119, 80, 0.7)',
    scrollbarThumbHoverHex: 'rgba(87, 62, 40, 0.95)',
    cardShapeClass: 'rounded-t-[3rem] rounded-b-2xl border-t-2 border-t-[#A37750]/40 ring-1 ring-[#EDDFD1]',
    cardHeaderShapeClass: 'rounded-2xl bg-[#A37750]/10 border border-[#A37750]/20',
    cardBorderDecoration: 'shadow-[0_8px_30px_rgb(163,119,80,0.12)]',
    cardLayoutVariant: 'standard',
  },
  'watercolor-garden': {
    id: 'watercolor-garden',
    name: 'Jardín de Hadas Pastel',
    badge: 'Flores de Acuarela & Ensueño',
    description: 'Pinceladas frescas, pétalos en vuelo y paleta juvenil pastel para una fiesta de quince al aire libre.',
    bgHex: '#F8FBF8',
    secondaryBgHex: '#EDF5ED',
    primaryColorHex: '#1A291E',
    accentColorHex: '#528B62',
    bgClass: 'bg-[#F8FBF8]',
    cardBgClass: 'bg-white/95 text-[#1A291E] shadow-sm border border-[#D1E6D6]',
    textPrimaryClass: 'text-[#1A291E]',
    textSecondaryClass: 'text-[#528B62]',
    accentClass: 'text-[#528B62] bg-[#F2FAF4] border-[#D1E6D6]',
    borderClass: 'border-[#D1E6D6]',
    envelopeClass: 'bg-[#31573B]',
    envelopeLidClass: 'bg-[#24422C]',
    sealBg: 'bg-gradient-to-br from-[#77B88A] via-[#528B62] to-[#31573B] text-[#FFF] shadow-green-900/30',
    sealText: 'text-white',
    fontDisplay: 'font-["Playfair_Display"]',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'watercolor',
    transitionType: 'watercolor-garden',
    scrollbarTrackHex: 'rgba(209, 230, 214, 0.5)',
    scrollbarThumbHex: 'rgba(82, 139, 98, 0.7)',
    scrollbarThumbHoverHex: 'rgba(49, 87, 59, 0.95)',
    cardShapeClass: 'rounded-t-[3rem] rounded-b-2xl border-t-2 border-t-[#528B62]/40 ring-1 ring-[#D1E6D6]',
    cardHeaderShapeClass: 'rounded-2xl bg-[#528B62]/10 border border-[#528B62]/20',
    cardBorderDecoration: 'shadow-[0_8px_30px_rgb(82,139,98,0.12)]',
    cardLayoutVariant: 'standard',
  },
  'dark-luxury': {
    id: 'dark-luxury',
    name: 'Gala Nocturna Diamante Negro',
    badge: 'Noche Glamour',
    description: 'Contraste audaz y vanguardista de fondo negro terciopelo con tiara y tipografía en oro pulido.',
    bgHex: '#121214',
    secondaryBgHex: '#1A1A1E',
    primaryColorHex: '#FFFFFF',
    accentColorHex: '#E2B874',
    bgClass: 'bg-[#121214]',
    cardBgClass: 'bg-[#1A1A1E] text-stone-100 shadow-xl border border-[#33312B]',
    textPrimaryClass: 'text-white',
    textSecondaryClass: 'text-[#E2B874]',
    accentClass: 'text-[#E2B874] bg-[#24221C] border-[#3D3728]',
    borderClass: 'border-[#33312B]',
    envelopeClass: 'bg-[#1E1C18]',
    envelopeLidClass: 'bg-[#151411]',
    sealBg: 'bg-gradient-to-br from-[#F5D89A] via-[#E2B874] to-[#A87B30] text-[#121214] shadow-amber-500/20',
    sealText: 'text-stone-950 font-bold',
    fontDisplay: 'font-["Playfair_Display"]',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'luxury',
    transitionType: 'celestial-night',
    scrollbarTrackHex: 'rgba(26, 26, 30, 0.8)',
    scrollbarThumbHex: 'rgba(226, 184, 116, 0.65)',
    scrollbarThumbHoverHex: 'rgba(245, 216, 154, 0.95)',
    cardShapeClass: 'rounded-2xl border border-[#33312B] ring-1 ring-[#E2B874]/30',
    cardHeaderShapeClass: 'rounded-xl bg-[#E2B874]/10 border border-[#E2B874]/30',
    cardBorderDecoration: 'shadow-[0_10px_35px_rgba(0,0,0,0.6)]',
    cardLayoutVariant: 'standard',
  },
  'boho-chic': {
    id: 'boho-chic',
    name: 'Boho Princesa & Destellos',
    badge: 'Bohemio & Ensueño',
    description: 'Estilo rústico elegante con flores silvestres y toques dorados juveniles.',
    bgHex: '#FAF8F4',
    secondaryBgHex: '#F4ECE4',
    primaryColorHex: '#2B231D',
    accentColorHex: '#C0705E',
    bgClass: 'bg-[#FAF8F4]',
    cardBgClass: 'bg-white/95 text-[#2B231D] shadow-sm border border-[#ECD9CE]',
    textPrimaryClass: 'text-[#2B231D]',
    textSecondaryClass: 'text-[#C0705E]',
    accentClass: 'text-[#C0705E] bg-[#FCF4EE] border-[#ECD9CE]',
    borderClass: 'border-[#ECD9CE]',
    envelopeClass: 'bg-[#664036]',
    envelopeLidClass: 'bg-[#4E3029]',
    sealBg: 'bg-gradient-to-br from-[#E29A8A] via-[#C0705E] to-[#664036] text-[#FFF] shadow-rose-900/30',
    sealText: 'text-white',
    fontDisplay: 'font-["Playfair_Display"]',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'boho',
    transitionType: 'boho-pampas',
    scrollbarTrackHex: 'rgba(236, 217, 206, 0.5)',
    scrollbarThumbHex: 'rgba(192, 112, 94, 0.7)',
    scrollbarThumbHoverHex: 'rgba(102, 64, 54, 0.95)',
    cardShapeClass: 'rounded-t-[3rem] rounded-b-2xl border-t-2 border-t-[#C0705E]/40 ring-1 ring-[#ECD9CE]',
    cardHeaderShapeClass: 'rounded-2xl bg-[#C0705E]/10 border border-[#C0705E]/20',
    cardBorderDecoration: 'shadow-[0_8px_30px_rgb(192,112,94,0.12)]',
    cardLayoutVariant: 'standard',
  },
  'minimal-editorial': {
    id: 'minimal-editorial',
    name: 'Vogue & Moda Juvenil',
    badge: 'Alta Costura XV',
    description: 'Tipografía refinada estilo revista de modas, líneas minimalistas y porte elegante de debutante.',
    bgHex: '#FAFAFA',
    secondaryBgHex: '#F0F0F0',
    primaryColorHex: '#111111',
    accentColorHex: '#444444',
    bgClass: 'bg-[#FAFAFA]',
    cardBgClass: 'bg-white text-[#111111] shadow-sm border border-[#E0E0E0]',
    textPrimaryClass: 'text-[#111111]',
    textSecondaryClass: 'text-[#444444]',
    accentClass: 'text-[#111111] bg-[#F5F5F5] border-[#E0E0E0]',
    borderClass: 'border-[#E0E0E0]',
    envelopeClass: 'bg-[#222222]',
    envelopeLidClass: 'bg-[#141414]',
    sealBg: 'bg-stone-900 text-white shadow-stone-900/40',
    sealText: 'text-white',
    fontDisplay: 'font-["Playfair_Display"]',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'minimal',
    transitionType: 'minimal-editorial',
    scrollbarTrackHex: 'rgba(224, 224, 224, 0.5)',
    scrollbarThumbHex: 'rgba(68, 68, 68, 0.6)',
    scrollbarThumbHoverHex: 'rgba(17, 17, 17, 0.9)',
    cardShapeClass: 'rounded-none border border-[#E0E0E0]',
    cardHeaderShapeClass: 'rounded-none bg-stone-50 border border-stone-200',
    cardBorderDecoration: 'shadow-[0_4px_24px_rgba(0,0,0,0.06)]',
    cardLayoutVariant: 'standard',
  },
  'terracotta-sunset': {
    id: 'terracotta-sunset',
    name: 'Atardecer Dorado & Coral',
    badge: 'Cálido & Radiante',
    description: 'Tonos melocotón, coral y sol de media tarde para una quinceañera cálida y luminosa.',
    bgHex: '#FCF9F6',
    secondaryBgHex: '#F7EDE4',
    primaryColorHex: '#30221A',
    accentColorHex: '#BA684A',
    bgClass: 'bg-[#FCF9F6]',
    cardBgClass: 'bg-white/95 text-[#30221A] shadow-sm border border-[#EED7C8]',
    textPrimaryClass: 'text-[#30221A]',
    textSecondaryClass: 'text-[#BA684A]',
    accentClass: 'text-[#BA684A] bg-[#FAF0E8] border-[#EED7C8]',
    borderClass: 'border-[#EED7C8]',
    envelopeClass: 'bg-[#663624]',
    envelopeLidClass: 'bg-[#4F2A1C]',
    sealBg: 'bg-gradient-to-br from-[#DE8B6D] via-[#BA684A] to-[#663624] text-[#FFF] shadow-amber-900/30',
    sealText: 'text-white',
    fontDisplay: 'font-["Playfair_Display"]',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'terracotta',
    transitionType: 'desert-sunset',
    scrollbarTrackHex: 'rgba(238, 215, 200, 0.5)',
    scrollbarThumbHex: 'rgba(186, 104, 74, 0.7)',
    scrollbarThumbHoverHex: 'rgba(102, 54, 36, 0.95)',
    cardShapeClass: 'rounded-t-[3rem] rounded-b-2xl border-t-2 border-t-[#BA684A]/40 ring-1 ring-[#EED7C8]',
    cardHeaderShapeClass: 'rounded-2xl bg-[#BA684A]/10 border border-[#BA684A]/20',
    cardBorderDecoration: 'shadow-[0_8px_30px_rgb(186,104,74,0.12)]',
    cardLayoutVariant: 'standard',
  },
  'coastal-breeze': {
    id: 'coastal-breeze',
    name: 'Brisa Marina & Princesa Sirena',
    badge: 'Azul Aguamarina',
    description: 'Celeste cristalino, toques perla y brisa marina para celebraciones playeras o de jardín.',
    bgHex: '#F6FAFA',
    secondaryBgHex: '#EBF4F4',
    primaryColorHex: '#14272B',
    accentColorHex: '#3D7E87',
    bgClass: 'bg-[#F6FAFA]',
    cardBgClass: 'bg-white/95 text-[#14272B] shadow-sm border border-[#CDE1E3]',
    textPrimaryClass: 'text-[#14272B]',
    textSecondaryClass: 'text-[#3D7E87]',
    accentClass: 'text-[#3D7E87] bg-[#F0F7F8] border-[#CDE1E3]',
    borderClass: 'border-[#CDE1E3]',
    envelopeClass: 'bg-[#224A50]',
    envelopeLidClass: 'bg-[#18363A]',
    sealBg: 'bg-gradient-to-br from-[#68B1BC] via-[#3D7E87] to-[#224A50] text-[#FFF] shadow-teal-900/30',
    sealText: 'text-white',
    fontDisplay: 'font-["Playfair_Display"]',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'coastal',
    transitionType: 'ocean-tide',
    scrollbarTrackHex: 'rgba(205, 225, 227, 0.5)',
    scrollbarThumbHex: 'rgba(61, 126, 135, 0.7)',
    scrollbarThumbHoverHex: 'rgba(34, 74, 80, 0.95)',
    cardShapeClass: 'rounded-t-[3rem] rounded-b-2xl border-t-2 border-t-[#3D7E87]/40 ring-1 ring-[#CDE1E3]',
    cardHeaderShapeClass: 'rounded-2xl bg-[#3D7E87]/10 border border-[#3D7E87]/20',
    cardBorderDecoration: 'shadow-[0_8px_30px_rgb(61,126,135,0.12)]',
    cardLayoutVariant: 'standard',
  },
};

export const applyXvThemeScrollbar = (styleId: CardStyleId) => {
  if (typeof document === 'undefined') return;
  const theme = XV_CARD_THEMES[styleId] || XV_CARD_THEMES['romantic-floral'];
  const root = document.documentElement;
  root.style.setProperty('--theme-scrollbar-track', theme.scrollbarTrackHex);
  root.style.setProperty('--theme-scrollbar-thumb', theme.scrollbarThumbHex);
  root.style.setProperty('--theme-scrollbar-thumb-hover', theme.scrollbarThumbHoverHex);
};
