import { WeddingSettings } from '../types.ts';

export const DEFAULT_WEDDING_SETTINGS: WeddingSettings = {
  id: 1,
  userId: 1,
  ownerUid: 'demo-user-master',
  slug: 'boda-sofia-alejandro',
  coupleNames: 'Sofía & Alejandro',
  hashtag: '#BodaSofyAle2026',
  eventDate: '2026-11-28',
  eventTime: '17:00',
  ceremonyVenue: 'Parroquia San Francisco de Asís',
  ceremonyAddress: 'Calle de los Olivos 142, Centro Histórico',
  ceremonyMapsUrl: 'https://maps.google.com/?q=Parroquia+San+Francisco+de+Asis',
  ceremonyEmbedUrl: '',
  ceremonyPlaceQuery: 'Parroquia San Francisco de Asís',
  ceremonyTime: '17:00',
  receptionVenue: 'Hacienda Los Arcángeles',
  receptionAddress: 'Km 14.5 Carretera Real, Valle Encantado',
  receptionMapsUrl: 'https://maps.google.com/?q=Hacienda+Los+Arcangeles',
  receptionEmbedUrl: '',
  receptionPlaceQuery: 'Hacienda Los Arcángeles',
  receptionTime: '19:30',
  dressCode: 'Formal / Traje Oscuro y Vestido Largo',
  dressCodeDescription: 'Agradecemos no usar blanco, marfil o champagne reservado para la novia.',
  dressCodePalette: JSON.stringify(['#1C2D37', '#9E7D47', '#D4AF37', '#D8C7B8', '#4A5B52']),
  dressCodeMenTitle: 'Hombres',
  dressCodeMenDescription: 'Traje formal oscuro, camisa clara y corbata elegante.',
  dressCodeWomenTitle: 'Mujeres',
  dressCodeWomenDescription: 'Vestido largo de noche o cóctel sofisticado.',
  dressCodeFootwearNote: 'Se sugiere calzado cómodo para jardín empedrado.',
  dressCodeProhibitedColors: 'Blanco, Marfil y Champagne',
  dressCodeStylePreset: 'formal',
  dressCodeWomanOutfit: 'long-gown',
  dressCodeManOutfit: 'suit',
  itinerary: JSON.stringify([
    { time: '17:00', title: 'Ceremonia Religiosa', desc: 'Parroquia San Francisco de Asís', icon: 'church' },
    { time: '18:30', title: 'Cóctel de Bienvenida', desc: 'Jardín de los Naranjos', icon: 'cocktail' },
    { time: '20:00', title: 'Banquete & Brindis', desc: 'Salón Principal', icon: 'utensils' },
    { time: '22:00', title: 'Fiesta & DJ', desc: 'Pista de baile y barra libre', icon: 'music' },
    { time: '02:00', title: 'Tornaboda & Chilaquiles', desc: 'Terraza Nocturna', icon: 'moon' },
  ]),
  giftRegistry: JSON.stringify([
    {
      type: 'bank',
      title: 'Transferencia Bancaria',
      accountNumber: '1234-5678-9012-3456',
      clabe: '012180012345678901',
      bankName: 'BBVA',
      beneficiary: 'Sofía Martínez / Alejandro Ruiz',
      concept: 'Boda Sofía & Alejandro',
    },
    {
      type: 'store',
      title: 'Mesa de Regalos Liverpool',
      url: 'https://mesaderegalos.liverpool.com.mx',
      eventNumber: '51298472',
    },
    {
      type: 'honeymoon',
      title: 'Fondo Luna de Miel en Bali',
      description: 'Tu aportación para experiencias inolvidables en nuestro primer viaje de casados',
      url: 'https://paypal.me/boda',
    },
  ]),
  coverPhoto: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1600&q=80',
  secondaryPhoto: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=80',
  heroImageFit: 'cover',
  heroImagePosition: 'center',
  heroOverlayOpacity: 40,
  heroEnableScrollBlur: true,
  cardStyle: 'classic-gold',
  envelopeColor: '#2C2B29',
  waxSealText: 'S&A',
  waxSealColor: '#C5A059',
  audioUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=acoustic-guitars-ambient-uplifting-112705.mp3',
  audioTitle: 'Acoustic Romance - Guitarra Suave',
  audioAutoplay: false,
  welcomeMessage: '¡Nos casamos! Nos hace inmensa ilusión celebrar nuestro amor',
  welcomeSubtitle: 'Nos emociona compartir este día tan especial contigo. Aquí encontrarás todos los detalles y ubicaciones de nuestra celebración.',
  heroDateFormat: 'dd.mm.aaaa',
  heroCustomDateText: '',
  heroQuote: 'El amor todo lo sufre, todo lo cree, todo lo espera, todo lo soporta.',
  heroVerse: '1 Corintios 13:7',
  heroShowCountdown: false,
  heroShowRsvpButton: false,
  heroShowIcon: false,
  heroShowGuestPill: false,
  showItinerary: true,
  showLocations: true,
  showDressCode: true,
  showGiftRegistry: true,
  showPhotoGallery: true,
  galleryExternalAlbumUrl: '',
  galleryExternalAlbumTitle: 'Álbum en Google Photos',
  galleryExternalAlbumType: 'google_photos',
  showVideoMemories: false,
  showGuestbook: false,
  showHotels: false,
  showRsvpSection: true,
  bankName: 'BBVA',
  bankBeneficiary: 'Sofía Martínez / Alejandro Ruiz',
  bankAccountNumber: '1234 5678 9012 3456',
  bankClabe: '012180012345678901',
  bankCardNumber: '',
  bankConcept: 'Boda Sofía & Alejandro',
  bankCurrency: 'MXN',
  enableBankTransfer: true,
  enableStoreRegistry: true,
  enableEnvelopeGift: false,
  envelopeGiftMessage: 'Lluvia de sobres: Si deseas hacernos un regalo en efectivo el día del evento, dispondremos de un cofre especial en la recepción.',
  customStoreItems: [],
  rsvpDeadline: '2026-10-30',
  contactPhone: '+52 55 1234 5678',
  contactEmail: 'boda.sofyale@gmail.com',
  isPublished: true,
};
