import { CardStyleId, CardThemeConfig } from '../types.ts';

export const CARD_THEMES: Record<CardStyleId, CardThemeConfig> = {
  'classic-gold': {
    id: 'classic-gold',
    name: 'Natural Olive & Marfil',
    badge: 'Tonos Naturales & Olivo',
    description: 'Guirnaldas botánicas de olivo y marfil cálido, estética serena y clásica mediterránea.',
    bgHex: '#FDFCF0',
    secondaryBgHex: '#FAF9F0',
    primaryColorHex: '#1a1a1a',
    accentColorHex: '#5A5A40',
    bgClass: 'bg-[#FDFCF0]',
    cardBgClass: 'bg-white text-[#1a1a1a] shadow-sm border border-[#E5E2D0]',
    textPrimaryClass: 'text-[#1a1a1a]',
    textSecondaryClass: 'text-[#5A5A40]',
    accentClass: 'text-[#5A5A40] bg-[#F9F7EF] border-[#E5E2D0]',
    borderClass: 'border-[#E5E2D0]',
    envelopeClass: 'bg-[#5A5A40]',
    envelopeLidClass: 'bg-[#484833]',
    sealBg: 'bg-gradient-to-br from-[#7D8C7A] via-[#5A5A40] to-[#3d3d2c] text-[#FDFCF0] shadow-stone-900/30',
    sealText: 'text-[#FDFCF0]',
    fontDisplay: 'font-["Playfair_Display"]',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'gold',
    transitionType: 'organic-wave',
    scrollbarTrackHex: 'rgba(229, 226, 208, 0.45)',
    scrollbarThumbHex: 'rgba(125, 140, 122, 0.7)',
    scrollbarThumbHoverHex: 'rgba(90, 90, 64, 0.95)',
    cardShapeClass: 'rounded-t-[2.5rem] rounded-b-2xl border-t-2 border-t-[#5A5A40]/40 ring-1 ring-[#E5E2D0]',
    cardHeaderShapeClass: 'rounded-2xl bg-[#5A5A40]/10 border border-[#5A5A40]/20',
    cardBorderDecoration: 'shadow-[0_8px_30px_rgb(90,90,64,0.08)]',
    cardLayoutVariant: 'standard',
  },
  'romantic-floral': {
    id: 'romantic-floral',
    name: 'Rosa Romántico & Flores',
    badge: 'Acuarela Floral',
    description: 'Arco de rosas inglesas en acuarela, tonos empolvados y cisnes reales entrelazados.',
    bgHex: '#FAF7F5',
    secondaryBgHex: '#F8F2EE',
    primaryColorHex: '#2A1F1D',
    accentColorHex: '#8A6D65',
    bgClass: 'bg-[#FAF7F5]',
    cardBgClass: 'bg-white/95 text-stone-900 shadow-sm border border-[#E8DFD8]',
    textPrimaryClass: 'text-stone-900',
    textSecondaryClass: 'text-[#8A6D65]',
    accentClass: 'text-[#8A6D65] bg-[#F8F2EE] border-[#E8DFD8]',
    borderClass: 'border-[#E8DFD8]',
    envelopeClass: 'bg-[#7c5957]',
    envelopeLidClass: 'bg-[#674745]',
    sealBg: 'bg-gradient-to-br from-[#A88079] via-[#7c5957] to-[#543432] text-[#FDFCF0] shadow-stone-900/30',
    sealText: 'text-[#FDFCF0]',
    fontDisplay: 'font-["Playfair_Display"]',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'floral',
    transitionType: 'floral-arch',
    scrollbarTrackHex: 'rgba(232, 223, 216, 0.5)',
    scrollbarThumbHex: 'rgba(168, 128, 121, 0.7)',
    scrollbarThumbHoverHex: 'rgba(138, 109, 101, 0.95)',
    cardShapeClass: 'rounded-tl-[3rem] rounded-br-[3rem] rounded-tr-xl rounded-bl-xl border-t-2 border-t-[#8A6D65]/40 border-b-2 border-b-[#8A6D65]/30 ring-1 ring-[#E8DFD8]',
    cardHeaderShapeClass: 'rounded-tl-2xl rounded-br-2xl bg-[#8A6D65]/10 border border-[#8A6D65]/20',
    cardBorderDecoration: 'shadow-[0_8px_30px_rgb(138,109,101,0.10)]',
    cardLayoutVariant: 'standard',
  },
  'boho-chic': {
    id: 'boho-chic',
    name: 'Boho Terracota & Salvia',
    badge: 'Naturaleza & Boho',
    description: 'Hierbas de pampas secas, sol naciente bohemio y acentos cálidos de terracota.',
    bgHex: '#FAF8F2',
    secondaryBgHex: '#F3EFE6',
    primaryColorHex: '#2D2A26',
    accentColorHex: '#B26E59',
    bgClass: 'bg-[#FAF8F2]',
    cardBgClass: 'bg-white/95 text-[#3D3D3D] shadow-sm border border-[#E8DFD2]',
    textPrimaryClass: 'text-[#2D2A26]',
    textSecondaryClass: 'text-[#7D8C7A]',
    accentClass: 'text-[#B26E59] bg-[#FAF3ED] border-[#E8DFD2]',
    borderClass: 'border-[#E8DFD2]',
    envelopeClass: 'bg-[#7D8C7A]',
    envelopeLidClass: 'bg-[#687665]',
    sealBg: 'bg-gradient-to-br from-[#96A693] via-[#7D8C7A] to-[#556353] text-[#FDFCF0] shadow-stone-900/30',
    sealText: 'text-[#FDFCF0]',
    fontDisplay: 'font-["Montserrat"] font-semibold',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'boho',
    transitionType: 'boho-pampas',
    scrollbarTrackHex: 'rgba(232, 223, 210, 0.5)',
    scrollbarThumbHex: 'rgba(178, 110, 89, 0.65)',
    scrollbarThumbHoverHex: 'rgba(143, 79, 61, 0.95)',
    cardShapeClass: 'rounded-t-[3.5rem] rounded-b-xl border-t-4 border-t-[#B26E59] border-x border-b border-[#E8DFD2]',
    cardHeaderShapeClass: 'rounded-full bg-[#B26E59]/10 border border-[#B26E59]/25',
    cardBorderDecoration: 'shadow-[0_8px_30px_rgb(178,110,89,0.12)]',
    cardLayoutVariant: 'standard',
  },
  'minimal-editorial': {
    id: 'minimal-editorial',
    name: 'Minimalista Editorial',
    badge: 'Vogue & Lino Natural',
    description: 'Líneas limpias, tipografía geométrica de alta costura y un diseño sereno contemporáneo.',
    bgHex: '#F9F7EF',
    secondaryBgHex: '#F2EFE3',
    primaryColorHex: '#141414',
    accentColorHex: '#4A4A3A',
    bgClass: 'bg-[#F9F7EF]',
    cardBgClass: 'bg-white text-[#1a1a1a] shadow-sm border border-[#141414]',
    textPrimaryClass: 'text-[#1a1a1a]',
    textSecondaryClass: 'text-[#5A5A40]',
    accentClass: 'text-[#1a1a1a] bg-[#FAF9F0] border-[#E5E2D0]',
    borderClass: 'border-[#141414]',
    envelopeClass: 'bg-[#2A2A26]',
    envelopeLidClass: 'bg-[#1D1D1A]',
    sealBg: 'bg-gradient-to-br from-[#5A5A40] via-[#3D3D2C] to-[#1D1D1A] text-[#FDFCF0] shadow-black/40',
    sealText: 'text-[#FDFCF0]',
    fontDisplay: 'font-["Montserrat"] uppercase tracking-widest',
    fontBody: 'font-["Montserrat"] font-light',
    ornamentStyle: 'minimal',
    transitionType: 'minimal-editorial',
    scrollbarTrackHex: 'rgba(229, 226, 208, 0.45)',
    scrollbarThumbHex: 'rgba(90, 90, 64, 0.6)',
    scrollbarThumbHoverHex: 'rgba(20, 20, 20, 0.9)',
    cardShapeClass: 'rounded-none border-2 border-stone-900 border-l-[6px] border-l-stone-900 shadow-none',
    cardHeaderShapeClass: 'rounded-none bg-stone-900 text-white border border-stone-900',
    cardBorderDecoration: 'shadow-[6px_6px_0px_0px_rgba(20,20,20,0.9)]',
    cardLayoutVariant: 'standard',
  },
  'dark-luxury': {
    id: 'dark-luxury',
    name: 'Noche Olivo & Bronce',
    badge: 'Lujo Nocturno',
    description: 'Constelaciones estelares doradas y fondos oscuros en verde olivo profundo y bronce.',
    bgHex: '#1F211D',
    secondaryBgHex: '#181A16',
    primaryColorHex: '#FFFFFF',
    accentColorHex: '#E5C07B',
    bgClass: 'bg-[#1F211D]',
    cardBgClass: 'bg-gradient-to-b from-[#282B25] to-[#1C1E19] text-white shadow-2xl border border-[#C5A059]/40',
    textPrimaryClass: 'text-white',
    textSecondaryClass: 'text-stone-200',
    accentClass: 'text-[#E5C07B] bg-[#333830] border-[#5A5A40]',
    borderClass: 'border-[#5A5A40]',
    envelopeClass: 'bg-[#181A16]',
    envelopeLidClass: 'bg-[#121411]',
    sealBg: 'bg-gradient-to-br from-[#C5A059] via-[#947437] to-[#5A5A40] text-[#FDFCF0] shadow-black/60',
    sealText: 'text-[#FDFCF0]',
    fontDisplay: 'font-["Cinzel"]',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'stars',
    transitionType: 'celestial-night',
    scrollbarTrackHex: 'rgba(24, 26, 22, 0.7)',
    scrollbarThumbHex: 'rgba(90, 90, 64, 0.8)',
    scrollbarThumbHoverHex: 'rgba(197, 160, 89, 0.95)',
    cardShapeClass: 'rounded-2xl border-2 border-[#C5A059]/50 shadow-[0_0_25px_rgba(197,160,89,0.15)] ring-1 ring-[#C5A059]/30 relative overflow-hidden backdrop-blur-xs',
    cardHeaderShapeClass: 'rounded-xl bg-[#C5A059]/15 border border-[#C5A059]/40 text-[#C5A059]',
    cardBorderDecoration: 'shadow-[0_0_30px_rgba(197,160,89,0.2)]',
    cardLayoutVariant: 'standard',
  },
  'watercolor-garden': {
    id: 'watercolor-garden',
    name: 'Jardín Botánico & Salvia',
    badge: 'Jardín & Follaje',
    description: 'Ramas de eucalipto en acuarela fresca, caligrafía romántica y tonos salvia exuberantes.',
    bgHex: '#FAFBF6',
    secondaryBgHex: '#F2F5EB',
    primaryColorHex: '#1D261C',
    accentColorHex: '#526B50',
    bgClass: 'bg-[#FAFBF6]',
    cardBgClass: 'bg-white/95 text-[#1a1a1a] shadow-sm border border-[#DCE4DA]',
    textPrimaryClass: 'text-[#1a1a1a]',
    textSecondaryClass: 'text-[#526B50]',
    accentClass: 'text-[#526B50] bg-[#F4F7F1] border-[#DCE4DA]',
    borderClass: 'border-[#DCE4DA]',
    envelopeClass: 'bg-[#526B50]',
    envelopeLidClass: 'bg-[#3E523C]',
    sealBg: 'bg-gradient-to-br from-[#7D947B] via-[#526B50] to-[#31422F] text-[#FDFCF0] shadow-stone-900/40',
    sealText: 'text-[#FDFCF0]',
    fontDisplay: 'font-["Alex_Brush"] text-3xl',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'garden',
    transitionType: 'watercolor-garden',
    scrollbarTrackHex: 'rgba(220, 228, 218, 0.5)',
    scrollbarThumbHex: 'rgba(125, 148, 123, 0.7)',
    scrollbarThumbHoverHex: 'rgba(82, 107, 80, 0.95)',
    cardShapeClass: 'rounded-tr-[3.5rem] rounded-bl-[3.5rem] rounded-tl-2xl rounded-br-2xl border-t-2 border-t-[#526B50]/50 border-b-2 border-b-[#526B50]/40 ring-1 ring-[#DCE4DA]',
    cardHeaderShapeClass: 'rounded-tr-2xl rounded-bl-2xl bg-[#526B50]/10 border border-[#526B50]/25',
    cardBorderDecoration: 'shadow-[0_8px_30px_rgb(82,107,80,0.10)]',
    cardLayoutVariant: 'standard',
  },
  'royal-navy': {
    id: 'royal-navy',
    name: 'Azul Imperial & Oro Real',
    badge: 'Realeza & Gala',
    description: 'Azul zafiro medianoche majestuoso con filigranas de coronas barrocas y acentos dorados reales.',
    bgHex: '#0B1320',
    secondaryBgHex: '#080E18',
    primaryColorHex: '#FFFFFF',
    accentColorHex: '#F3CF68',
    bgClass: 'bg-[#0B1320]',
    cardBgClass: 'bg-gradient-to-b from-[#131E30] via-[#0E1726] to-[#0A111C] text-white border-2 border-[#D4AF37]/60 shadow-[0_0_35px_rgba(212,175,55,0.25)]',
    textPrimaryClass: 'text-white',
    textSecondaryClass: 'text-slate-200',
    accentClass: 'text-[#F3CF68] bg-[#1E293B]/90 border-[#D4AF37]/50 shadow-inner',
    borderClass: 'border-[#D4AF37]/40',
    envelopeClass: 'bg-[#0D1B2A]',
    envelopeLidClass: 'bg-[#07101B]',
    sealBg: 'bg-gradient-to-br from-[#F5D77F] via-[#D4AF37] to-[#8C6B1C] text-[#0B1320] shadow-black/60',
    sealText: 'text-[#0B1320]',
    fontDisplay: 'font-["Cinzel"] font-bold tracking-wider',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'crown',
    transitionType: 'royal-crest',
    scrollbarTrackHex: 'rgba(11, 19, 32, 0.8)',
    scrollbarThumbHex: 'rgba(212, 175, 55, 0.75)',
    scrollbarThumbHoverHex: 'rgba(245, 215, 127, 0.95)',
    cardShapeClass: 'rounded-none border-y-4 border-y-[#D4AF37] border-x-2 border-x-[#D4AF37]/40 relative clip-heraldic',
    cardHeaderShapeClass: 'rounded-none bg-[#D4AF37]/20 border-b-2 border-b-[#D4AF37]/50 text-[#D4AF37] px-4 py-2 uppercase tracking-widest',
    cardBorderDecoration: 'shadow-[0_16px_50px_rgba(13,27,42,0.8),inset_0_0_30px_rgba(212,175,55,0.08)]',
    cardLayoutVariant: 'royal-crest',
  },
  'terracotta-sunset': {
    id: 'terracotta-sunset',
    name: 'Atardecer Terracota & Cobre',
    badge: 'Atardecer & Desierto',
    description: 'Calidez crepuscular con tonalidades cobre, horizontes desérticos y destellos de arena cálida.',
    bgHex: '#FAF4EE',
    secondaryBgHex: '#F3E8DD',
    primaryColorHex: '#2E1A16',
    accentColorHex: '#E07A5F',
    bgClass: 'bg-[#FAF4EE]',
    cardBgClass: 'bg-[#FFFDFB] text-[#2E1A16] shadow-sm border-2 border-dashed border-[#E07A5F]/60',
    textPrimaryClass: 'text-[#2E1A16]',
    textSecondaryClass: 'text-[#A05A48]',
    accentClass: 'text-[#E07A5F] bg-[#FDF0EB] border-[#EACEC1]',
    borderClass: 'border-[#EACEC1]',
    envelopeClass: 'bg-[#8F4A38]',
    envelopeLidClass: 'bg-[#733829]',
    sealBg: 'bg-gradient-to-br from-[#F4A261] via-[#E07A5F] to-[#8F4A38] text-[#FDFCF0] shadow-stone-900/40',
    sealText: 'text-[#FDFCF0]',
    fontDisplay: 'font-["Playfair_Display"] italic',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'sunset',
    transitionType: 'desert-sunset',
    scrollbarTrackHex: 'rgba(234, 206, 193, 0.5)',
    scrollbarThumbHex: 'rgba(224, 122, 95, 0.7)',
    scrollbarThumbHoverHex: 'rgba(160, 90, 72, 0.95)',
    cardShapeClass: 'rounded-3xl border-2 border-[#E07A5F]/70 relative ticket-scalloped',
    cardHeaderShapeClass: 'rounded-full bg-[#E07A5F]/15 border border-[#E07A5F]/35 px-4 py-1.5',
    cardBorderDecoration: 'shadow-[0_10px_35px_rgba(224,122,95,0.18)]',
    cardLayoutVariant: 'desert-ticket',
  },
  'lavender-provence': {
    id: 'lavender-provence',
    name: 'Lavanda Provenzal & Lino',
    badge: 'Provenza & Lavanda',
    description: 'Espigas florecidas de lavanda francesa, mariposas sutiles y tonos lila empolvados.',
    bgHex: '#F8F6FB',
    secondaryBgHex: '#EFEBF5',
    primaryColorHex: '#231B2B',
    accentColorHex: '#7B6D8D',
    bgClass: 'bg-[#F8F6FB]',
    cardBgClass: 'bg-gradient-to-b from-[#FFFFFF] via-[#FAF8FD] to-[#F3EFF8] text-[#231B2B] shadow-sm border border-[#DDD6E8]',
    textPrimaryClass: 'text-[#231B2B]',
    textSecondaryClass: 'text-[#7B6D8D]',
    accentClass: 'text-[#7B6D8D] bg-[#F3EFF8] border-[#DDD6E8]',
    borderClass: 'border-[#DDD6E8]',
    envelopeClass: 'bg-[#675677]',
    envelopeLidClass: 'bg-[#534362]',
    sealBg: 'bg-gradient-to-br from-[#9D8BB0] via-[#7B6D8D] to-[#4A3E56] text-[#FDFCF0] shadow-stone-900/35',
    sealText: 'text-[#FDFCF0]',
    fontDisplay: 'font-["Playfair_Display"]',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'lavender',
    transitionType: 'lavender-field',
    scrollbarTrackHex: 'rgba(221, 214, 232, 0.5)',
    scrollbarThumbHex: 'rgba(123, 109, 141, 0.7)',
    scrollbarThumbHoverHex: 'rgba(74, 62, 86, 0.95)',
    cardShapeClass: 'rounded-t-[4.5rem] rounded-b-xl border-t-3 border-t-[#7B6D8D] border-x border-b border-[#DDD6E8] ring-4 ring-[#7B6D8D]/10',
    cardHeaderShapeClass: 'rounded-full bg-[#7B6D8D]/15 border border-[#7B6D8D]/35',
    cardBorderDecoration: 'shadow-[0_12px_36px_rgba(123,109,141,0.16)]',
    cardLayoutVariant: 'provence-parchment',
  },
  'emerald-botanical': {
    id: 'emerald-botanical',
    name: 'Esmeralda Selvático & Oro',
    badge: 'Selva Exótica & Oro',
    description: 'Hojas exuberantes de monstera y palmas tropicales en verde esmeralda profundo con destellos oro.',
    bgHex: '#081710',
    secondaryBgHex: '#050F0A',
    primaryColorHex: '#FFFFFF',
    accentColorHex: '#74C69D',
    bgClass: 'bg-[#081710]',
    cardBgClass: 'bg-gradient-to-b from-[#0F261B] to-[#06140D] text-white border border-[#52B788]/50 shadow-[0_0_35px_rgba(82,183,136,0.2)]',
    textPrimaryClass: 'text-white',
    textSecondaryClass: 'text-emerald-100',
    accentClass: 'text-[#74C69D] bg-[#1B4332]/80 border-[#52B788]/50',
    borderClass: 'border-[#52B788]/40',
    envelopeClass: 'bg-[#1B4332]',
    envelopeLidClass: 'bg-[#0E271D]',
    sealBg: 'bg-gradient-to-br from-[#74C69D] via-[#2D6A4F] to-[#081C15] text-[#FDFCF0] shadow-black/50',
    sealText: 'text-[#FDFCF0]',
    fontDisplay: 'font-["Montserrat"] font-bold tracking-wide',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'monstera',
    transitionType: 'emerald-palms',
    scrollbarTrackHex: 'rgba(8, 23, 16, 0.8)',
    scrollbarThumbHex: 'rgba(82, 183, 136, 0.75)',
    scrollbarThumbHoverHex: 'rgba(116, 198, 157, 0.95)',
    cardShapeClass: 'rounded-3xl border-2 border-emerald-500/40 relative overflow-hidden backdrop-blur-md',
    cardHeaderShapeClass: 'rounded-xl bg-[#52B788]/20 border border-[#52B788]/45 text-[#52B788]',
    cardBorderDecoration: 'shadow-[0_16px_45px_rgba(5,15,10,0.85),inset_0_1px_1px_rgba(255,255,255,0.15)]',
    cardLayoutVariant: 'emerald-luxury',
  },
  'coastal-breeze': {
    id: 'coastal-breeze',
    name: 'Brisa Marina & Arena Blanca',
    badge: 'Mediterráneo & Mar',
    description: 'Olas marinas en azul mediterráneo, conchas de nácar perladas y arena blanca bajo el sol.',
    bgHex: '#F2F8FA',
    secondaryBgHex: '#E5F1F5',
    primaryColorHex: '#0F2942',
    accentColorHex: '#2B6CB0',
    bgClass: 'bg-[#F2F8FA]',
    cardBgClass: 'bg-white/95 text-[#0F2942] shadow-sm border border-[#CCE3ED]',
    textPrimaryClass: 'text-[#0F2942]',
    textSecondaryClass: 'text-[#2B6CB0]',
    accentClass: 'text-[#2B6CB0] bg-[#EBF4F8] border-[#CCE3ED]',
    borderClass: 'border-[#CCE3ED]',
    envelopeClass: 'bg-[#1E4E80]',
    envelopeLidClass: 'bg-[#153B63]',
    sealBg: 'bg-gradient-to-br from-[#63B3ED] via-[#2B6CB0] to-[#1A365D] text-[#FDFCF0] shadow-stone-900/35',
    sealText: 'text-[#FDFCF0]',
    fontDisplay: 'font-["Playfair_Display"]',
    fontBody: 'font-["Cormorant_Garamond"]',
    ornamentStyle: 'seashell',
    transitionType: 'ocean-tide',
    scrollbarTrackHex: 'rgba(204, 227, 237, 0.5)',
    scrollbarThumbHex: 'rgba(43, 108, 176, 0.7)',
    scrollbarThumbHoverHex: 'rgba(15, 41, 66, 0.95)',
    cardShapeClass: 'rounded-tl-[4rem] rounded-tr-lg rounded-br-[4rem] rounded-bl-lg border-2 border-[#2B6CB0]/40 border-t-4 border-t-[#2B6CB0] border-b-4 border-b-[#2B6CB0]',
    cardHeaderShapeClass: 'rounded-tl-2xl rounded-br-2xl bg-[#2B6CB0]/15 border border-[#2B6CB0]/30',
    cardBorderDecoration: 'shadow-[0_10px_35px_rgba(43,108,176,0.15)]',
    cardLayoutVariant: 'nautical-passport',
  },
  'champagne-glam': {
    id: 'champagne-glam',
    name: 'Champagne Glam & Perlas',
    badge: 'Art Déco & Perlas',
    description: 'Gala Art Déco con destellos de perlas nacaradas, tonos champaña dorados y geometría de los años 20.',
    bgHex: '#FAF7F0',
    secondaryBgHex: '#F3EDE0',
    primaryColorHex: '#261E14',
    accentColorHex: '#C39B60',
    bgClass: 'bg-[#FAF7F0]',
    cardBgClass: 'bg-white/95 text-[#261E14] shadow-sm border border-[#E8DEC8]',
    textPrimaryClass: 'text-[#261E14]',
    textSecondaryClass: 'text-[#967746]',
    accentClass: 'text-[#C39B60] bg-[#FAF3E6] border-[#E8DEC8]',
    borderClass: 'border-[#E8DEC8]',
    envelopeClass: 'bg-[#8F6E3B]',
    envelopeLidClass: 'bg-[#73562B]',
    sealBg: 'bg-gradient-to-br from-[#E5C992] via-[#C39B60] to-[#6E4F21] text-[#261E14] shadow-stone-900/35',
    sealText: 'text-[#261E14]',
    fontDisplay: 'font-["Cinzel"] tracking-wider',
    fontBody: 'font-["Montserrat"] font-light',
    ornamentStyle: 'art-deco',
    transitionType: 'champagne-sparkle',
    scrollbarTrackHex: 'rgba(232, 222, 200, 0.5)',
    scrollbarThumbHex: 'rgba(195, 155, 96, 0.7)',
    scrollbarThumbHoverHex: 'rgba(110, 79, 33, 0.95)',
    cardShapeClass: 'rounded-none border-4 border-double border-[#C39B60] ring-1 ring-[#C39B60]/40 relative artdeco-frame',
    cardHeaderShapeClass: 'rounded-none bg-[#C39B60]/20 border-2 border-[#C39B60]/40',
    cardBorderDecoration: 'shadow-[0_12px_40px_rgba(195,155,96,0.22)]',
    cardLayoutVariant: 'artdeco-plaque',
  },
};

/**
 * Dynamically applies theme-reactive scrollbar colors to root document
 */
export function applyThemeScrollbar(cardStyle?: CardStyleId | string) {
  if (typeof document === 'undefined') return;
  const theme = (cardStyle && CARD_THEMES[cardStyle as CardStyleId]) || CARD_THEMES['classic-gold'];
  const root = document.documentElement;
  root.style.setProperty('--scrollbar-track', theme.scrollbarTrackHex || 'rgba(229, 226, 208, 0.45)');
  root.style.setProperty('--scrollbar-thumb', theme.scrollbarThumbHex || 'rgba(125, 140, 122, 0.7)');
  root.style.setProperty('--scrollbar-thumb-hover', theme.scrollbarThumbHoverHex || 'rgba(90, 90, 64, 0.95)');
}
